before_script: npm install -g harp
script: bash ./deploy.sh
language: node_js
node_js:
  - 5.7.1
env:
  global:
    - GH_REF: github.com/halestudio/github-project-public.git
    - secure: "wiEqj48GEImXRxPzDqechkGa4o2qC8V62b9YRTK4AuaY/rCe8n/goRui1C0uRitbZMFmGgegdmuy3+3NxuJhVeunlCel4OUxiZGN6aL8et02h/a2rmpJmjCTrO0+7V/3EYtADBnAy+IXV0zKx4aTpDrwcL6p5aGzrh9EqxG1UbW4V2/c7RAOJE/bnL6iFlUga5jaE1hfS0mMxocGPsmKX2j+x1QWn81zcT8LA7lgZUn6xk3vwVQB96FjiIYoeJeA+/9Mnda+/EXc8Mv99frI4jjG/iIMVBvVh/3PsNQ2vwuW5UzSBkYSjDWHxkTdn9NvDysQdnwy6hOEA/2oXV6lKpt3iB5FIK3tGjMrT4EXPreQAq6TUjyfOr+oQIvAw3bA2ybrb0uDsLCJi1CO9TfnxhrXH7sMChfudO4QgHdggBk0TZ9zUFFsdaP2oFTaSf724kGvPN7tGl+Yr+rMDa8d1+thbs3vCZlvRE8TGFaFTbS6q4M7qG2E5pLhq7D7h6YUKSYHDEKrL5ZxGSShy1U4lDtmGqYp6MhfBF5c2ym6Ugx4sakJfpLOMvz2rSqOjAI3tKFs6Z+ZBI1XxQgKULRiqEmKyz5aPnkeKccoSGDrdzJKO/EhR91IWyfYbRXJhcfp14VcYctBOJUf0C3RdrlZZ6POuenQ6uwPSfnS9st4b6Y="
branches:
  only:
    - master
